import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-black dark:text-white bg-white dark:bg-slate-700">
        {children}
      </body>
    </html>
  );
}
