import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function AuthLayout({ children }) {
  return <div>{children}</div>;
}
